rules:
  github-app:
    ignore:
      - reusable_terraform_plan_apply.yml
  self-repository:
    ignore:
      - modernisation-platform-account.yml
      - new-environment.yml
      - scheduled-baseline-extended-matrix.yml