## This file is automatically generated based on what regions are enabled in an AWS account
## and what regions SecurityHub is available in.

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "ap-northeast-1" {
  provider = aws.ap-northeast-1
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "ap-northeast-1-aws-foundational" {
  provider      = aws.ap-northeast-1
  depends_on    = [aws_securityhub_account.ap-northeast-1]
  standards_arn = "arn:aws:securityhub:ap-northeast-1::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "ap-northeast-1-cis" {
  provider      = aws.ap-northeast-1
  depends_on    = [aws_securityhub_account.ap-northeast-1]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "ap-northeast-1-pci" {
  provider      = aws.ap-northeast-1
  depends_on    = [aws_securityhub_account.ap-northeast-1]
  standards_arn = "arn:aws:securityhub:ap-northeast-1::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "ap-northeast-2" {
  provider = aws.ap-northeast-2
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "ap-northeast-2-aws-foundational" {
  provider      = aws.ap-northeast-2
  depends_on    = [aws_securityhub_account.ap-northeast-2]
  standards_arn = "arn:aws:securityhub:ap-northeast-2::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "ap-northeast-2-cis" {
  provider      = aws.ap-northeast-2
  depends_on    = [aws_securityhub_account.ap-northeast-2]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "ap-northeast-2-pci" {
  provider      = aws.ap-northeast-2
  depends_on    = [aws_securityhub_account.ap-northeast-2]
  standards_arn = "arn:aws:securityhub:ap-northeast-2::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "ap-south-1" {
  provider = aws.ap-south-1
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "ap-south-1-aws-foundational" {
  provider      = aws.ap-south-1
  depends_on    = [aws_securityhub_account.ap-south-1]
  standards_arn = "arn:aws:securityhub:ap-south-1::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "ap-south-1-cis" {
  provider      = aws.ap-south-1
  depends_on    = [aws_securityhub_account.ap-south-1]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "ap-south-1-pci" {
  provider      = aws.ap-south-1
  depends_on    = [aws_securityhub_account.ap-south-1]
  standards_arn = "arn:aws:securityhub:ap-south-1::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "ap-southeast-1" {
  provider = aws.ap-southeast-1
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "ap-southeast-1-aws-foundational" {
  provider      = aws.ap-southeast-1
  depends_on    = [aws_securityhub_account.ap-southeast-1]
  standards_arn = "arn:aws:securityhub:ap-southeast-1::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "ap-southeast-1-cis" {
  provider      = aws.ap-southeast-1
  depends_on    = [aws_securityhub_account.ap-southeast-1]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "ap-southeast-1-pci" {
  provider      = aws.ap-southeast-1
  depends_on    = [aws_securityhub_account.ap-southeast-1]
  standards_arn = "arn:aws:securityhub:ap-southeast-1::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "ap-southeast-2" {
  provider = aws.ap-southeast-2
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "ap-southeast-2-aws-foundational" {
  provider      = aws.ap-southeast-2
  depends_on    = [aws_securityhub_account.ap-southeast-2]
  standards_arn = "arn:aws:securityhub:ap-southeast-2::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "ap-southeast-2-cis" {
  provider      = aws.ap-southeast-2
  depends_on    = [aws_securityhub_account.ap-southeast-2]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "ap-southeast-2-pci" {
  provider      = aws.ap-southeast-2
  depends_on    = [aws_securityhub_account.ap-southeast-2]
  standards_arn = "arn:aws:securityhub:ap-southeast-2::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "ca-central-1" {
  provider = aws.ca-central-1
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "ca-central-1-aws-foundational" {
  provider      = aws.ca-central-1
  depends_on    = [aws_securityhub_account.ca-central-1]
  standards_arn = "arn:aws:securityhub:ca-central-1::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "ca-central-1-cis" {
  provider      = aws.ca-central-1
  depends_on    = [aws_securityhub_account.ca-central-1]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "ca-central-1-pci" {
  provider      = aws.ca-central-1
  depends_on    = [aws_securityhub_account.ca-central-1]
  standards_arn = "arn:aws:securityhub:ca-central-1::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "eu-central-1" {
  provider = aws.eu-central-1
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "eu-central-1-aws-foundational" {
  provider      = aws.eu-central-1
  depends_on    = [aws_securityhub_account.eu-central-1]
  standards_arn = "arn:aws:securityhub:eu-central-1::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "eu-central-1-cis" {
  provider      = aws.eu-central-1
  depends_on    = [aws_securityhub_account.eu-central-1]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "eu-central-1-pci" {
  provider      = aws.eu-central-1
  depends_on    = [aws_securityhub_account.eu-central-1]
  standards_arn = "arn:aws:securityhub:eu-central-1::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "eu-north-1" {
  provider = aws.eu-north-1
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "eu-north-1-aws-foundational" {
  provider      = aws.eu-north-1
  depends_on    = [aws_securityhub_account.eu-north-1]
  standards_arn = "arn:aws:securityhub:eu-north-1::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "eu-north-1-cis" {
  provider      = aws.eu-north-1
  depends_on    = [aws_securityhub_account.eu-north-1]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "eu-north-1-pci" {
  provider      = aws.eu-north-1
  depends_on    = [aws_securityhub_account.eu-north-1]
  standards_arn = "arn:aws:securityhub:eu-north-1::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "eu-west-1" {
  provider = aws.eu-west-1
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "eu-west-1-aws-foundational" {
  provider      = aws.eu-west-1
  depends_on    = [aws_securityhub_account.eu-west-1]
  standards_arn = "arn:aws:securityhub:eu-west-1::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "eu-west-1-cis" {
  provider      = aws.eu-west-1
  depends_on    = [aws_securityhub_account.eu-west-1]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "eu-west-1-pci" {
  provider      = aws.eu-west-1
  depends_on    = [aws_securityhub_account.eu-west-1]
  standards_arn = "arn:aws:securityhub:eu-west-1::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "eu-west-2" {
  provider = aws.eu-west-2
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "eu-west-2-aws-foundational" {
  provider      = aws.eu-west-2
  depends_on    = [aws_securityhub_account.eu-west-2]
  standards_arn = "arn:aws:securityhub:eu-west-2::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "eu-west-2-cis" {
  provider      = aws.eu-west-2
  depends_on    = [aws_securityhub_account.eu-west-2]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "eu-west-2-pci" {
  provider      = aws.eu-west-2
  depends_on    = [aws_securityhub_account.eu-west-2]
  standards_arn = "arn:aws:securityhub:eu-west-2::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "eu-west-3" {
  provider = aws.eu-west-3
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "eu-west-3-aws-foundational" {
  provider      = aws.eu-west-3
  depends_on    = [aws_securityhub_account.eu-west-3]
  standards_arn = "arn:aws:securityhub:eu-west-3::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "eu-west-3-cis" {
  provider      = aws.eu-west-3
  depends_on    = [aws_securityhub_account.eu-west-3]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "eu-west-3-pci" {
  provider      = aws.eu-west-3
  depends_on    = [aws_securityhub_account.eu-west-3]
  standards_arn = "arn:aws:securityhub:eu-west-3::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "sa-east-1" {
  provider = aws.sa-east-1
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "sa-east-1-aws-foundational" {
  provider      = aws.sa-east-1
  depends_on    = [aws_securityhub_account.sa-east-1]
  standards_arn = "arn:aws:securityhub:sa-east-1::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "sa-east-1-cis" {
  provider      = aws.sa-east-1
  depends_on    = [aws_securityhub_account.sa-east-1]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "sa-east-1-pci" {
  provider      = aws.sa-east-1
  depends_on    = [aws_securityhub_account.sa-east-1]
  standards_arn = "arn:aws:securityhub:sa-east-1::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "us-east-1" {
  provider = aws.us-east-1
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "us-east-1-aws-foundational" {
  provider      = aws.us-east-1
  depends_on    = [aws_securityhub_account.us-east-1]
  standards_arn = "arn:aws:securityhub:us-east-1::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "us-east-1-cis" {
  provider      = aws.us-east-1
  depends_on    = [aws_securityhub_account.us-east-1]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "us-east-1-pci" {
  provider      = aws.us-east-1
  depends_on    = [aws_securityhub_account.us-east-1]
  standards_arn = "arn:aws:securityhub:us-east-1::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "us-east-2" {
  provider = aws.us-east-2
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "us-east-2-aws-foundational" {
  provider      = aws.us-east-2
  depends_on    = [aws_securityhub_account.us-east-2]
  standards_arn = "arn:aws:securityhub:us-east-2::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "us-east-2-cis" {
  provider      = aws.us-east-2
  depends_on    = [aws_securityhub_account.us-east-2]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "us-east-2-pci" {
  provider      = aws.us-east-2
  depends_on    = [aws_securityhub_account.us-east-2]
  standards_arn = "arn:aws:securityhub:us-east-2::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "us-west-1" {
  provider = aws.us-west-1
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "us-west-1-aws-foundational" {
  provider      = aws.us-west-1
  depends_on    = [aws_securityhub_account.us-west-1]
  standards_arn = "arn:aws:securityhub:us-west-1::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "us-west-1-cis" {
  provider      = aws.us-west-1
  depends_on    = [aws_securityhub_account.us-west-1]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "us-west-1-pci" {
  provider      = aws.us-west-1
  depends_on    = [aws_securityhub_account.us-west-1]
  standards_arn = "arn:aws:securityhub:us-west-1::standards/pci-dss/v/3.2.1"
}

# Enable SecurityHub in each available region
resource "aws_securityhub_account" "us-west-2" {
  provider = aws.us-west-2
}

# Enable Standard: AWS Foundational Security Best Practices
resource "aws_securityhub_standards_subscription" "us-west-2-aws-foundational" {
  provider      = aws.us-west-2
  depends_on    = [aws_securityhub_account.us-west-2]
  standards_arn = "arn:aws:securityhub:us-west-2::standards/aws-foundational-security-best-practices/v/1.0.0"
}

# Enable Standard: CIS AWS Foundations
resource "aws_securityhub_standards_subscription" "us-west-2-cis" {
  provider      = aws.us-west-2
  depends_on    = [aws_securityhub_account.us-west-2]
  standards_arn = "arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0"
}

# Enable Standard: PCI DSS v3.2.1
resource "aws_securityhub_standards_subscription" "us-west-2-pci" {
  provider      = aws.us-west-2
  depends_on    = [aws_securityhub_account.us-west-2]
  standards_arn = "arn:aws:securityhub:us-west-2::standards/pci-dss/v/3.2.1"
}

