# NOTE: This file is automatically generated within Terraform. Please commit it whenever it changes.

provider "aws" {
  alias  = "shared-services-dev"
  region = "eu-west-2"
  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

# Configure an assumable role from the Modernisation Platform
resource "aws_iam_role" "assumable-modernisation-platform-role" {
  name               = "AssumableByModernisationPlatform"
  assume_role_policy = data.aws_iam_policy_document.assumable-by-modernisation-platform.json
  provider           = aws.shared-services-dev
}

resource "aws_iam_role_policy_attachment" "modernisation-platform" {
  role       = aws_iam_role.assumable-modernisation-platform-role.name
  policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
  provider   = aws.shared-services-dev
}
