## This file is automatically generated based on what regions are enabled in an AWS account.

provider "aws" {
  region = "ap-northeast-1"
  alias  = "shared-services-dev-ap-northeast-1"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "ap-northeast-2"
  alias  = "shared-services-dev-ap-northeast-2"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "ap-south-1"
  alias  = "shared-services-dev-ap-south-1"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "ap-southeast-1"
  alias  = "shared-services-dev-ap-southeast-1"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "ap-southeast-2"
  alias  = "shared-services-dev-ap-southeast-2"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "ca-central-1"
  alias  = "shared-services-dev-ca-central-1"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "eu-central-1"
  alias  = "shared-services-dev-eu-central-1"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "eu-north-1"
  alias  = "shared-services-dev-eu-north-1"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "eu-west-1"
  alias  = "shared-services-dev-eu-west-1"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "eu-west-2"
  alias  = "shared-services-dev-eu-west-2"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "eu-west-3"
  alias  = "shared-services-dev-eu-west-3"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "sa-east-1"
  alias  = "shared-services-dev-sa-east-1"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "us-east-1"
  alias  = "shared-services-dev-us-east-1"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "us-east-2"
  alias  = "shared-services-dev-us-east-2"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "us-west-1"
  alias  = "shared-services-dev-us-west-1"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

provider "aws" {
  region = "us-west-2"
  alias  = "shared-services-dev-us-west-2"

  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.account_ids["shared-services-dev"]}:role/OrganizationAccountAccessRole"
  }
}

module "cross-account-access-shared-services-dev" {
  source = "github.com/ministryofjustice/modernisation-platform-terraform-cross-account-access"
  providers = {
    aws = aws.shared-services-dev-eu-west-2
  }
  account_id = local.modernisation_platform_account.id
  policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
  role_name  = "ModernisationPlatformAccess"
}

module "baselines-shared-services-dev" {
  source = "github.com/ministryofjustice/modernisation-platform-terraform-baselines"
  providers = {
    # Default and replication regions
    aws                    = aws.shared-services-dev-eu-west-2
    aws.replication-region = aws.shared-services-dev-eu-west-1

    # Other regions
    aws.ap-northeast-1 = aws.shared-services-dev-ap-northeast-1
    aws.ap-northeast-2 = aws.shared-services-dev-ap-northeast-2
    aws.ap-south-1     = aws.shared-services-dev-ap-south-1
    aws.ap-southeast-1 = aws.shared-services-dev-ap-southeast-1
    aws.ap-southeast-2 = aws.shared-services-dev-ap-southeast-2
    aws.ca-central-1   = aws.shared-services-dev-ca-central-1
    aws.eu-central-1   = aws.shared-services-dev-eu-central-1
    aws.eu-north-1     = aws.shared-services-dev-eu-north-1
    aws.eu-west-1      = aws.shared-services-dev-eu-west-1
    aws.eu-west-2      = aws.shared-services-dev-eu-west-2
    aws.eu-west-3      = aws.shared-services-dev-eu-west-3
    aws.sa-east-1      = aws.shared-services-dev-sa-east-1
    aws.us-east-1      = aws.shared-services-dev-us-east-1
    aws.us-east-2      = aws.shared-services-dev-us-east-2
    aws.us-west-1      = aws.shared-services-dev-us-west-1
    aws.us-west-2      = aws.shared-services-dev-us-west-2
  }
  root_account_id = local.root_account.master_account_id
  tags            = local.environments
}
