---
name: Automation PR test
on:
  workflow_dispatch:

jobs:
  create-environments-pr:
    runs-on: ubuntu-latest
    environment: dpr-onboarding
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: core-repo
      
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ministryofjustice
          repositories: modernisation-platform-environments

     
      - name: Checkout environments repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: ministryofjustice/modernisation-platform-environments
          path: modernisation-platform-environments
          token: ${{ steps.app-token.outputs.token }}


      - name: Create new configuration
        run: |
          mkdir -p ./modernisation-platform-environments/terraform/environments/sprinkler
          cat > ./modernisation-platform-environments/terraform/environments/sprinkler/test.tf <<EOF
          data "http" "test" {
            url = "https://raw.githubusercontent.com/ministryofjustice/modernisation-platform/main/environments/sprinkler.json"
          }
          EOF
      - name: Commit changes to GitHub
        run: bash ./core-repo/scripts/git-setup.sh
      
      - name: Commit and Create PR
        uses: ministryofjustice/modernisation-platform-github-actions/signed-commit@2988728879704953e739f82ac926d37931c6d01b
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          remote_repository: "ministryofjustice/modernisation-platform-environments"
          remote_repository_path: "./modernisation-platform-environments"
          pr_title: "Automated PR test"
          pr_body: |
            This PR was automatically created by the test onboarding workflow.