name: Enforce Workflow Change Authorisation
on:
  pull_request:
permissions:
  contents: read
  pull-requests: read
  id-token: write
jobs:
  validate-workflow-change-author:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "Destroy"