name: "Test Workflow"

on:
  push:
    branches:
      - feature/6888-reusable-terraform-plan-apply

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Message
        run: echo "Workflow triggered successfully!"