name: "Terraform: modernisation-platform-account"

on:
  push:
    branches:
      - feature/6888-reusable-terraform-plan-apply

jobs:
  reusable-plan:
    uses: ./.github/workflows/reusable_terraform_plan_test_km.yml
    with:
      aws_region: "eu-west-2"
      tf_workspace: "modernisation-platform-account"
      working_directory: "terraform/modernisation-platform-account"
      role_name: "github-actions"
      aws_account_id: ".modernisation_platform_account_id"
    secrets:
      environment_management: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENTS }}
      ACCOUNT_NUMBER: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_ID }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}