name: "Terraform: New environment"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: true
  AWS_REGION: "eu-west-2"
  TEMPLATE_ID: "1f0f5ccc-0f67-4ee2-942f-6e48804828ea"
  EXPECTED_TEMPLATE_VERSION: "1" # Update with your expected template version
  RATE_THRESHOLD: 100
  APP_ID: 2013696

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for updating PR comments

defaults:
  run:
    shell: bash

jobs:

  fetch-secrets:
    uses: ministryofjustice/modernisation-platform-github-actions/.github/workflows/aws-secrets-management.yml@5c713c93eea694829b1bd3f410d0b235053318ce # v4.0.0
    secrets:
      MODERNISATION_PLATFORM_ACCOUNT_NUMBER: ${{ secrets.MODERNISATION_PLATFORM_ACCOUNT_NUMBER }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}

  check-environments-deployment-plan:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && github.event_name != 'workflow_dispatch'
    needs: fetch-secrets
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Test workflow changes
        run: |
          echo "Test"
     
