name: Reusable Scheduled Baselines Workflow

on:
  workflow_call:
    inputs:

        JOB_NAME:
          required: true
          type: string
          description: "The job name for logging / debugging purposes"

        AWS_REGION:
            required: true
            type: string
            description: "The aws region"           

        environment_management:
            required: true
            type: string
            description: "The Account List"

        TF_WORKSPACE:
            required: true
            type: string
            description: "The workspace"

        working_directory:
            required: true
            type: string
            description: "The terraform working directory"
    secrets:

      PASSPHRASE:
        required: true

permissions: {}

env:
  STATE_FILE: ${{ inputs.working_directory }}/errored.tfstate
            
jobs:

    main:
      permissions:
        id-token: write
        contents: read
      runs-on: ubuntu-latest
      name: "Job - ${{ inputs.JOB_NAME }}"
      steps:
        - name: Log Job Name
          run: | 
            echo "Job Name: " ${{ inputs.JOB_NAME }}
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        - name: Decrypt Secrets
          uses: ministryofjustice/modernisation-platform-github-actions/decrypt-secrets@d2d07632db53d17c9760c0c2c06f22a37bd3f0a1 # v6.0.1
          with:
            environment_management: ${{ inputs.environment_management }}
            slack_webhook_url: ${{ inputs.slack_webhook_url }}
            PASSPHRASE: ${{ secrets.PASSPHRASE }}
        - name: Set Account Number
          run: |
            ACCOUNT_NUMBER=$(jq -r -e '.modernisation_platform_account_id' <<< "$ENVIRONMENT_MANAGEMENT")
            ACCOUNT_ID=$(jq -r -e '.account_ids[$TF_WORKSPACE]' <<< "$ENVIRONMENT_MANAGEMENT")
            echo "::add-mask::$ACCOUNT_NUMBER"
            echo ACCOUNT_NUMBER=$ACCOUNT_NUMBER >> $GITHUB_ENV
            echo ACCOUNT_ID=$ACCOUNT_ID >> $GITHUB_ENV
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6.1.1
          with:
            role-to-assume: arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions
            role-session-name: githubactionsrolesession
            aws-region: ${{ inputs.AWS_REGION }}
        - name: Remove Default VPC
          run: bash ./scripts/internal/remove-default-vpc/remove_default_vpc_all_accounts.sh ${{ env.ACCOUNT_ID }}
      env:
        TF_WORKSPACE: ${{ inputs.TF_WORKSPACE }}
        STATE_PUSH_SUCCESSFUL: false
