name: Check Inactive Superadmins

on:
  schedule:
    - cron: '30 9 */100,1-7 * 1'

env:
    AWS_REGION: "eu-west-2"
    ENVIRONMENT_MANAGEMENT: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENTS }}
    GH_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}

permissions:
    id-token: write # This is required for requesting the JWT
    contents: read # This is required for actions/checkout
    issues: write # This is required to create issues
jobs:
  disable-login-for-inactive-superadmins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set Account Number
        run: echo "ACCOUNT_NUMBER=$(jq -r -e '.modernisation_platform_account_id' <<< $ENVIRONMENT_MANAGEMENT)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions"
          role-session-name: githubactionsrolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Fetch Inactive Superadmins
        run: bash ./scripts/internal/superadmins-inactivity-notification/check_inactive_users.sh
        env:
          threshold: 120

      - name: Disable Console Login
        run: bash ./scripts/internal/superadmins-inactivity-notification/disable_user_credentials.sh

  schedule-user-deletion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set Account Number
        run: echo "ACCOUNT_NUMBER=$(jq -r -e '.modernisation_platform_account_id' <<< $ENVIRONMENT_MANAGEMENT)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions"
          role-session-name: githubactionsrolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Fetch Inactive Superadmins
        run: bash ./scripts/internal/superadmins-inactivity-notification/check_inactive_users.sh
        env:
          threshold: 180

      - name: Create Deletion Issue
        run: bash ./scripts/internal/superadmins-inactivity-notification/superadmin_user_deletion_issue.sh