name: "Terraform: GitHub resources"

on:
  push:
    paths:
      - 'terraform/github/**'
    branches:
      # - feature/6888-reusable-terraform-plan-apply
      - main

  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read

jobs:
  terraform-github-plan:
    uses: ./.github/workflows/reusable_terraform_plan_test_km.yml
    with:
      working_directory: "terraform/github"
    secrets:
      environment_management: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENTS }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      TERRAFORM_GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}

  create-github-environments:
    runs-on: ubuntu-latest
    needs: [ terraform-github-plan ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0 # or "2" To retrieve the preceding commit.
      - name: Create GitHub member environments plan
        run: bash ./scripts/git-create-environments.sh
        env:
          DRY_RUN: true
          TERRAFORM_GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}